name: Backup Firestore

on:
  schedule:
    - cron:  '*/15 * * * *'

env:
  PROJECT_ID: e-commerce-getx-5b6a6
  BUCKET: gs://e-commerce_backup_bucket_test

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET